server:
  port: 3000

socket:
  port: 3001

database:
  type: 'sqlite'
  database: 'data/derq.db'
  entities: [ Site, Sensor, HealthStatus ]
  synchronize: true

web:
  url: 'http://localhost:3000/api'
